gedit-plugins: Add runtime dependency for the git plugin
Summary: Signed-off-by: Pierre-Yves <pyu@riseup.net>

Test Plan:
The below error doesn't occur anymore and the lines that have been changed/added/removes are flagged as expected
```
(org.gnome.gedit:1622): libpeas-WARNING **: 15:03:16.350: Error importing plugin 'git':
Traceback (most recent call last):
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib64/gedit/plugins/git/__init__.py", line 23, in <module>
    gi.require_version('Ggit', '1.0')
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Ggit not available
```

Reviewers: #triage_team, JoshStrobl

Reviewed By: #triage_team, JoshStrobl

Subscribers: JoshStrobl

Differential Revision: https://dev.getsol.us/D6881