glib2: Update glib2 to 2.52.2 and convert to package.yml
Summary:
* Bug fixes:
 Implement GContentType on OSX
 Increase performance for main loop
 gio/gosxappinfo.c uses deprecated LSFindApplicationForInfo
 gio/tests/appinfo build fails: gdesktopappinfo.c skipped
 on OS X
 gfileutils.c:330:3: error: ISO C90 forbids mixed
 declarations and code

* Translation updates:
 Indonesian

Test Plan:
content of the .eopkg's  looks ok but it needs
 to be validated someone with more expertise than me

Reviewers: #triage_team, ikey

Reviewed By: #triage_team, ikey

Subscribers: JoshStrobl, ikey, kyrios123

Differential Revision: https://dev.solus-project.com/D66