glances: Update to 4.1.2
**Changelog:**
- Fix: AttributeError: 'CpuPercent' object has no attribute 'cpu_percent'

Signed-off-by: Algent Albrahimi <algent@protonmail.com>