engrampa: Update to 1.28.2
**Summary**

- Fix extract of encrypted archives
- Fix volume split button in "Compress" window
- src/file-utils.c: Fix "error: implicit declaration of function ‘strcasecmp’..."
- fr-process.c: Setting error status