glibc: Revert to fix ld linker issues
**Summary**

Recently package builds have started showing ld linker issues of the form `undefined reference to __pthread_timedjoin_np64` and similar.
Examples of affected packages: `open-vm-tools`, `transmission`, `fastfetch`

The workaround was switching the build to clang tooling, but the actual cause seems to be this `glibc` commit: https://sourceware.org/git/?p=glibc.git;a=commit;h=dd535f4f19ef2b5c367a362af445ecadcf45401e

This patch changes our `glibc` build from the latest commit to the one right before the affected one, fixing the other package builds.

Signed-off-by: Thomas Staudinger <Staudi.Kaos@gmail.com>