libgtk-4: Ensure libgtk-4-devel requires vulkan-headers.
Will otherwise fail apps to compile due to missing file: `/usr/include/gtk-4.0/gdk/gdkvulkancontext.h:32:10: fatal error: vulkan/vulkan.h: No such file or directory`