python-spyder-kernels: Update python-spyder-kernels to 1.10.2
Summary:
**Changelog:**

- Warn when comm call creates text output
- Increase minimal required version of ipykernel
- Better test for non-interactive context
- Fix assignment detection in exclamation mark mode (Pdb)
- Fix recursive debugger
- Fix ImportError: cannot import name `leading_empty_lines`
- Treat `pkgs` path as a library
- Remove handlers that require direct code execution
- Add exception for quit and exit in `SpyderPdb`
- Add space after dot in a message
- Add extra validation to `is_module_installed`
- Avoid infinite hang when quitting external kernels
- Fix `get_cwd` permission errors

Signed-off-by: Algent Albrahimi <algent@protonmail.com>

Test Plan: Run a few python scrips using `spyder3`.

Reviewers: #triage_team, JoshStrobl

Reviewed By: #triage_team, JoshStrobl

Subscribers: JoshStrobl

Differential Revision: https://dev.getsol.us/D10603