nvidia-vaapi-driver: Update to 0.0.12 and add monitoring.yml
**Summary**

Changes:
- Single buffer export
- direct: Fix drm index loop condition
- Fix building with musl
- Unbreak build on FreeBSD
- src: Increase num_render_targets to 32 for Chromium
- Fix undefined reference to 'gettid'

Signed-off-by: Thomas Staudinger <Staudi.Kaos@gmail.com>